openapi: 3.0.0
info:
  title: レシピ提案API
  description: レシピを提案するAPPのAPI
  version: 1.0.0
  contact: 
      name: Yutaro
      url: http://www.example.com/support
      email: hogehoge@gmail.com
servers:
  - url: https://x3mh57lyz4.execute-api.ap-northeast-1.amazonaws.com/prod/apis
tags:
  - name: ingredients
    description: 食材関係
  - name: recipes
    description: レシピ関係

paths:
  /ingredients:
    $ref: "./apis/ingredients.yaml"
  /ingredients/{ingredient_id}:
   $ref: "./apis/ingredients/ingredient_id.yaml"
  
  /recipes:
    $ref: "./apis/recipes.yaml"
  /recipes/{recipe_id}:
    $ref: "./apis/recipes/recipe_id.yaml"


  /recipes/proposal:
    $ref: "./apis/recipes/proposal.yaml"