name: Deploy CDK App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Copy Flutter Environment Variable
      run: cd frontend/kondate_app && cp .env.template .env

    - name: Flutter Build
      run: cd frontend/kondate_app && flutter build web

    - name: Install dependencies
      run: cd backend/cdk && npm install

    - name: Run CDK Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-northeast-1' # AWSリージョンを指定
      run: cd backend/cdk && npx cdk deploy --all --require-approval never