name: Deploy CDK App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Copy Flutter Environment Variable
      run: cd frontend/kondate_app && cp .env.template .env

    - name: Copy Flutter Environment Variable for build object
      run: cd frontend/kondate_app && cp .env.template ./build/web/assets/.env

    # - name: echo
    #   run: echo ${{ secrets.AWS_ACCESS_KEY_ID }} && echo ${{ secrets.AWS_ACCESS_KEY_ID }} && echo ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Create Lambda Environment Variable
      run: echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} > backend/cdk/.env

    - name: Install dependencies
      run: cd backend/cdk && npm install
    
    - name: Install node api-modules
      run: cd backend/api-modules && npm install

    - name: Install node apis
      run: cd backend/apis && npm install


    - name: Run CDK Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-northeast-1' # AWSリージョンを指定
      run: cd backend/cdk && npx cdk deploy --all --require-approval never